stripe:
    publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
    secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>

algoliasearch:
    application_id: N0HHQGSRM0
    api_key: c524357aa05aa73a9fe1a54ec7caf46b
    search_key: cd21694b9db641c1ddfd693a2bde7cce

sentry_raven:
    dsn: 'https://4d5d36bc21464f5f8a69433f929c4cc4:4ed72f27b4fc4f6194ef1001c67d26dd@sentry.io/260644'
